# Generated by Django 3.2.23 on 2023-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('preview', models.CharField(max_length=250, verbose_name='Анонс')),
                ('description', models.TextField(verbose_name='Статья')),
                ('time', models.TimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
