# Generated by Django 3.2.23 on 2023-12-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
